export const WEAPON_IDS = [
  "pistol",
  "machineGun",
  "shotgun",
  "sniper",
  "burstRifle",
  "tripleShot",
  "quadShot",
  "arcShot",
  "wideShot",
  "scatterBlaster",
  "flameThrower",
  "poisonSprayer",
  "lightningGun",
  "iceBlaster",
  "acidCannon",
  "railgun",
  "laserRifle",
  "piercingRifle",
  "pulseCannon",
  "plasmaShot",
  "grenadeLauncher",
  "rocketLauncher",
  "clusterLauncher",
  "mineLayer",
  "shockBomb",
  "droneGun",
  "orbitingBlades",
  "energySatellites",
  "defenseTurret",
  "autoSentry",
  "boomerangBlade",
  "ricochetCannon",
  "chainLightningStaff",
  "voidBeam",
  "crystalBarrage",
  "magneticPulseGun",
  "temporalRepeater",
  "gravityCannon",
  "shatterRifle",
  "novaEmitter"
] as const;

export const BOSS_IDS = [
  "titan",
  "stormBringer",
  "infernoCore",
  "venomQueen",
  "ironColossus",
  "voidPhantom",
  "chronoBeast",
  "stormHydra",
  "orbitalTyrant",
  "finalWarden"
] as const;
