import type { WeaponDef } from "../../types";
import { defineWeapon, iconKey } from "./shared";

export const BASIC_WEAPONS: WeaponDef[] = [
  defineWeapon({
    id: "pistol",
    label: "Pistol",
    description: "Reliable sidearm with steady moderate rounds.",
    family: "basic",
    tier: 1,
    behaviorKind: "ballisticSingle",
    tags: [],
    visualKind: "bullet",
    impactKind: "hit",
    behaviorConfig: {},
    fireRateMs: 700,
    damage: 1,
    baseProjectiles: 1,
    projectileSpeed: 540,
    tint: 0xf5e7b5,
    spreadCapDeg: 24,
    iconKey: iconKey("pistol"),
    previewPattern: "single",
    muzzleFlashTint: 0xffe1aa,
    trailTint: 0xf4e0ac
  }),
  defineWeapon({
    id: "machineGun",
    label: "Machine Gun",
    description: "Fast stream of light rounds for focused pressure.",
    family: "basic",
    tier: 1,
    behaviorKind: "ballisticSingle",
    tags: [],
    visualKind: "bullet",
    impactKind: "hit",
    behaviorConfig: {},
    fireRateMs: 220,
    damage: 1,
    baseProjectiles: 1,
    projectileSpeed: 580,
    tint: 0xf0c46b,
    spreadCapDeg: 24,
    iconKey: iconKey("machineGun"),
    previewPattern: "stream",
    muzzleFlashTint: 0xffd481,
    projectileScale: 0.92,
    trailTint: 0xf3c46f
  }),
  defineWeapon({
    id: "shotgun",
    label: "Shotgun",
    description: "Heavy short-range blast for crowd carving.",
    family: "basic",
    tier: 1,
    behaviorKind: "fanSpread",
    tags: [],
    visualKind: "pellet",
    impactKind: "hit",
    behaviorConfig: {},
    fireRateMs: 1200,
    damage: 1,
    baseProjectiles: 5,
    projectileSpeed: 500,
    tint: 0xffa86f,
    spreadCapDeg: 40,
    iconKey: iconKey("shotgun"),
    previewPattern: "fan",
    muzzleFlashTint: 0xffbf8e,
    projectileScale: 1.05,
    trailTint: 0xffbb83
  }),
  defineWeapon({
    id: "sniper",
    label: "Sniper",
    description: "Slow powerful shot that pierces through lines.",
    family: "basic",
    tier: 1,
    behaviorKind: "pierceShot",
    tags: ["precision"],
    visualKind: "bullet",
    impactKind: "hit",
    behaviorConfig: {},
    fireRateMs: 1450,
    damage: 5,
    baseProjectiles: 1,
    projectileSpeed: 660,
    tint: 0xb8ebff,
    spreadCapDeg: 12,
    iconKey: iconKey("sniper"),
    previewPattern: "pierce",
    muzzleFlashTint: 0xd8f4ff,
    basePierce: 2,
    projectileScale: 1.1,
    trailTint: 0xb8ebff
  }),
  defineWeapon({
    id: "burstRifle",
    label: "Burst Rifle",
    description: "Three measured shots with controlled recoil.",
    family: "basic",
    tier: 1,
    behaviorKind: "ballisticBurst",
    tags: [],
    visualKind: "bullet",
    impactKind: "hit",
    behaviorConfig: {
      burstCount: 3,
      burstIntervalMs: 100
    },
    fireRateMs: 850,
    damage: 1,
    baseProjectiles: 1,
    projectileSpeed: 580,
    tint: 0xa6d87f,
    spreadCapDeg: 20,
    iconKey: iconKey("burstRifle"),
    previewPattern: "burst",
    muzzleFlashTint: 0xd9f6a6,
    burstCount: 3,
    burstIntervalMs: 100,
    trailTint: 0xb5e893
  })
] satisfies WeaponDef[];
