import type { WeaponDef } from "../../types";
import { defineWeapon, iconKey } from "./shared";

export const ELEMENTAL_WEAPONS: WeaponDef[] = [
  defineWeapon({
    id: "flameThrower",
    label: "Flame Thrower",
    description: "Short, hot stream that excels up close.",
    family: "elemental",
    tier: 2,
    behaviorKind: "streamDot",
    tags: ["fire"],
    visualKind: "flame",
    impactKind: "elemental",
    behaviorConfig: { shortLifetimeMs: 420 },
    fireRateMs: 150,
    damage: 0.6,
    baseProjectiles: 1,
    projectileSpeed: 340,
    tint: 0xff8a5e,
    spreadCapDeg: 20,
    iconKey: iconKey("flameThrower"),
    previewPattern: "stream",
    muzzleFlashTint: 0xffbb7a,
    projectileScale: 1.15,
    trailTint: 0xff8a5e,
    impactTint: 0xffa768
  }),
  defineWeapon({
    id: "poisonSprayer",
    label: "Poison Sprayer",
    description: "Wide toxic mist that lingers through pressure.",
    family: "elemental",
    tier: 2,
    behaviorKind: "streamDot",
    tags: ["poison"],
    visualKind: "flame",
    impactKind: "elemental",
    behaviorConfig: { shortLifetimeMs: 520 },
    fireRateMs: 180,
    damage: 0.7,
    baseProjectiles: 2,
    projectileSpeed: 330,
    tint: 0x8ce26f,
    spreadCapDeg: 24,
    iconKey: iconKey("poisonSprayer"),
    previewPattern: "stream",
    muzzleFlashTint: 0xbaf59f,
    projectileScale: 1.1,
    trailTint: 0x86dd7e,
    impactTint: 0x9aef87
  }),
  defineWeapon({
    id: "lightningGun",
    label: "Lightning Gun",
    description: "Snap-fast shock arcs into the nearest pack.",
    family: "elemental",
    tier: 2,
    behaviorKind: "chainCaster",
    tags: ["lightning"],
    visualKind: "lightning",
    impactKind: "chain",
    behaviorConfig: { chainTargets: 2, chainDamageMultiplier: 0.6, chainRange: 200 },
    fireRateMs: 620,
    damage: 2,
    baseProjectiles: 1,
    projectileSpeed: 640,
    tint: 0x92e7ff,
    spreadCapDeg: 10,
    iconKey: iconKey("lightningGun"),
    previewPattern: "chain",
    muzzleFlashTint: 0xd9fbff,
    projectileScale: 0.9,
    trailTint: 0x92e7ff,
    impactTint: 0xb5f1ff
  }),
  defineWeapon({
    id: "iceBlaster",
    label: "Ice Blaster",
    description: "Cold bolts with crisp, controllable spread.",
    family: "elemental",
    tier: 2,
    behaviorKind: "fanSpread",
    tags: ["ice"],
    visualKind: "bullet",
    impactKind: "elemental",
    behaviorConfig: {},
    fireRateMs: 980,
    damage: 1.4,
    baseProjectiles: 3,
    projectileSpeed: 520,
    tint: 0xa5dfff,
    spreadCapDeg: 20,
    iconKey: iconKey("iceBlaster"),
    previewPattern: "fan",
    muzzleFlashTint: 0xd7f2ff,
    projectileScale: 1,
    trailTint: 0xa5dfff
  }),
  defineWeapon({
    id: "acidCannon",
    label: "Acid Cannon",
    description: "Corrosive lob with splashy follow-through.",
    family: "elemental",
    tier: 2,
    behaviorKind: "rocketOrGrenade",
    tags: ["acid", "explosive"],
    visualKind: "grenade",
    impactKind: "elemental",
    behaviorConfig: { explosionRadius: 34, explosionDamage: 2.5 },
    fireRateMs: 1080,
    damage: 2,
    baseProjectiles: 1,
    projectileSpeed: 420,
    tint: 0xa5f27b,
    spreadCapDeg: 14,
    iconKey: iconKey("acidCannon"),
    previewPattern: "explosive",
    muzzleFlashTint: 0xd4ffb0,
    projectileScale: 1.12,
    trailTint: 0xa5f27b,
    impactTint: 0xc6ff94
  })
] satisfies WeaponDef[];
