import type { WeaponDef } from "../../types";
import { defineWeapon, iconKey } from "./shared";

export const EXOTIC_WEAPONS: WeaponDef[] = [
  defineWeapon({
    id: "boomerangBlade",
    label: "Boomerang Blade",
    description: "Forward throw that curves back through the lane.",
    family: "exotic",
    tier: 4,
    behaviorKind: "boomerangReturn",
    tags: ["bounce"],
    visualKind: "boomerang",
    impactKind: "hit",
    behaviorConfig: { returnDelayMs: 320 },
    fireRateMs: 820,
    damage: 1.9,
    baseProjectiles: 1,
    projectileSpeed: 470,
    tint: 0xf2df8f,
    spreadCapDeg: 18,
    iconKey: iconKey("boomerangBlade"),
    previewPattern: "single",
    muzzleFlashTint: 0xfff0b3,
    projectileScale: 1.08,
    trailTint: 0xf2df8f
  }),
  defineWeapon({
    id: "ricochetCannon",
    label: "Ricochet Cannon",
    description: "Heavy slugs built to rebound through packs.",
    family: "exotic",
    tier: 4,
    behaviorKind: "ballisticSingle",
    tags: ["bounce"],
    visualKind: "bullet",
    impactKind: "hit",
    behaviorConfig: {},
    fireRateMs: 980,
    damage: 2.3,
    baseProjectiles: 1,
    projectileSpeed: 560,
    tint: 0xa8ffd9,
    spreadCapDeg: 14,
    iconKey: iconKey("ricochetCannon"),
    previewPattern: "pierce",
    muzzleFlashTint: 0xd5ffec,
    projectileScale: 1.08,
    trailTint: 0xa8ffd9
  }),
  defineWeapon({
    id: "chainLightningStaff",
    label: "Chain Lightning Staff",
    description: "Reliable chaining arcs from a precise cast.",
    family: "exotic",
    tier: 4,
    behaviorKind: "chainCaster",
    tags: ["lightning"],
    visualKind: "lightning",
    impactKind: "chain",
    behaviorConfig: { chainTargets: 4, chainDamageMultiplier: 0.7, chainRange: 230 },
    fireRateMs: 900,
    damage: 2.6,
    baseProjectiles: 1,
    projectileSpeed: 700,
    tint: 0xa6f0ff,
    spreadCapDeg: 8,
    iconKey: iconKey("chainLightningStaff"),
    previewPattern: "chain",
    muzzleFlashTint: 0xe2fbff,
    trailTint: 0xa6f0ff
  }),
  defineWeapon({
    id: "voidBeam",
    label: "Void Beam",
    description: "Dark lance that drills through the center line.",
    family: "exotic",
    tier: 4,
    behaviorKind: "beam",
    tags: ["beam"],
    visualKind: "beam",
    impactKind: "beam",
    behaviorConfig: { beamWidth: 24, beamLength: 340, beamDurationMs: 110 },
    fireRateMs: 980,
    damage: 3.3,
    baseProjectiles: 1,
    projectileSpeed: 820,
    tint: 0xb59cff,
    spreadCapDeg: 6,
    iconKey: iconKey("voidBeam"),
    previewPattern: "beam",
    muzzleFlashTint: 0xdacabf,
    trailTint: 0xb59cff
  }),
  defineWeapon({
    id: "crystalBarrage",
    label: "Crystal Barrage",
    description: "Sharp crystal fan with dense clustered bursts.",
    family: "exotic",
    tier: 4,
    behaviorKind: "fanSpread",
    tags: ["precision"],
    visualKind: "pellet",
    impactKind: "hit",
    behaviorConfig: {},
    fireRateMs: 760,
    damage: 1.5,
    baseProjectiles: 4,
    projectileSpeed: 560,
    tint: 0xffb7f0,
    spreadCapDeg: 22,
    iconKey: iconKey("crystalBarrage"),
    previewPattern: "fan",
    muzzleFlashTint: 0xffdaf7,
    projectileScale: 0.94,
    trailTint: 0xffb7f0
  })
] satisfies WeaponDef[];
