import type { WeaponDef } from "../../types";
import { defineWeapon, iconKey } from "./shared";

export const EXPERIMENTAL_WEAPONS: WeaponDef[] = [
  defineWeapon({
    id: "magneticPulseGun",
    label: "Magnetic Pulse Gun",
    description: "Dense pulses that knock clusters off rhythm.",
    family: "experimental",
    tier: 4,
    behaviorKind: "ballisticBurst",
    tags: [],
    visualKind: "bullet",
    impactKind: "hit",
    behaviorConfig: { burstCount: 2, burstIntervalMs: 90 },
    fireRateMs: 760,
    damage: 2,
    baseProjectiles: 2,
    projectileSpeed: 520,
    tint: 0x9fd5ff,
    spreadCapDeg: 16,
    iconKey: iconKey("magneticPulseGun"),
    previewPattern: "burst",
    muzzleFlashTint: 0xcde7ff,
    burstCount: 2,
    burstIntervalMs: 90,
    projectileScale: 1.05,
    trailTint: 0x9fd5ff
  }),
  defineWeapon({
    id: "temporalRepeater",
    label: "Temporal Repeater",
    description: "Rapid repeating fire with jittery temporal echo.",
    family: "experimental",
    tier: 4,
    behaviorKind: "ballisticBurst",
    tags: [],
    visualKind: "bullet",
    impactKind: "hit",
    behaviorConfig: { burstCount: 4, burstIntervalMs: 80 },
    fireRateMs: 980,
    damage: 1.2,
    baseProjectiles: 1,
    projectileSpeed: 550,
    tint: 0xc9f18d,
    spreadCapDeg: 18,
    iconKey: iconKey("temporalRepeater"),
    previewPattern: "burst",
    muzzleFlashTint: 0xe6ffbc,
    burstCount: 4,
    burstIntervalMs: 80,
    trailTint: 0xc9f18d
  }),
  defineWeapon({
    id: "gravityCannon",
    label: "Gravity Cannon",
    description: "Crushing blast with a deep, slow burst front.",
    family: "experimental",
    tier: 4,
    behaviorKind: "rocketOrGrenade",
    tags: ["explosive"],
    visualKind: "grenade",
    impactKind: "explosive",
    behaviorConfig: { explosionRadius: 64, explosionDamage: 5.5 },
    fireRateMs: 1_420,
    damage: 3.6,
    baseProjectiles: 1,
    projectileSpeed: 360,
    tint: 0x9f9cff,
    spreadCapDeg: 10,
    iconKey: iconKey("gravityCannon"),
    previewPattern: "explosive",
    muzzleFlashTint: 0xc9c7ff,
    projectileScale: 1.2,
    trailTint: 0xb3b0ff,
    impactTint: 0xd7d2ff
  }),
  defineWeapon({
    id: "shatterRifle",
    label: "Shatter Rifle",
    description: "Precise shot that blooms into split fragments.",
    family: "experimental",
    tier: 4,
    behaviorKind: "fanSpread",
    tags: ["precision"],
    visualKind: "pellet",
    impactKind: "hit",
    behaviorConfig: {},
    fireRateMs: 880,
    damage: 1.6,
    baseProjectiles: 3,
    projectileSpeed: 610,
    tint: 0xb7f7ff,
    spreadCapDeg: 18,
    iconKey: iconKey("shatterRifle"),
    previewPattern: "fan",
    muzzleFlashTint: 0xddfdff,
    projectileScale: 0.96,
    trailTint: 0xb7f7ff
  }),
  defineWeapon({
    id: "novaEmitter",
    label: "Nova Emitter",
    description: "Controlled nova pulse that blooms from your aim line.",
    family: "experimental",
    tier: 4,
    behaviorKind: "novaBurst",
    tags: ["beam", "explosive"],
    visualKind: "nova",
    impactKind: "explosive",
    behaviorConfig: { novaCount: 10 },
    fireRateMs: 1_550,
    damage: 1.6,
    baseProjectiles: 6,
    projectileSpeed: 500,
    tint: 0xf7d889,
    spreadCapDeg: 30,
    iconKey: iconKey("novaEmitter"),
    previewPattern: "nova",
    muzzleFlashTint: 0xffefb4,
    projectileScale: 0.98,
    trailTint: 0xf7d889,
    impactTint: 0xffefb4
  })
] satisfies WeaponDef[];
