import type { WeaponDef } from "../../types";
import { defineWeapon, iconKey } from "./shared";

export const EXPLOSIVE_WEAPONS: WeaponDef[] = [
  defineWeapon({
    id: "grenadeLauncher",
    label: "Grenade Launcher",
    description: "Bouncy arc that ends in a compact blast.",
    family: "explosive",
    tier: 3,
    behaviorKind: "rocketOrGrenade",
    tags: ["explosive"],
    visualKind: "grenade",
    impactKind: "explosive",
    behaviorConfig: { explosionRadius: 42, explosionDamage: 3.5 },
    fireRateMs: 1180,
    damage: 2.2,
    baseProjectiles: 1,
    projectileSpeed: 400,
    tint: 0xffbb72,
    spreadCapDeg: 14,
    iconKey: iconKey("grenadeLauncher"),
    previewPattern: "explosive",
    muzzleFlashTint: 0xffdfaa,
    projectileScale: 1.16,
    trailTint: 0xffbb72,
    impactTint: 0xffd597
  }),
  defineWeapon({
    id: "rocketLauncher",
    label: "Rocket Launcher",
    description: "Straight heavy rocket with bigger detonation.",
    family: "explosive",
    tier: 3,
    behaviorKind: "rocketOrGrenade",
    tags: ["explosive"],
    visualKind: "rocket",
    impactKind: "explosive",
    behaviorConfig: { explosionRadius: 52, explosionDamage: 4.5 },
    fireRateMs: 1320,
    damage: 3.4,
    baseProjectiles: 1,
    projectileSpeed: 460,
    tint: 0xff8c67,
    spreadCapDeg: 12,
    iconKey: iconKey("rocketLauncher"),
    previewPattern: "explosive",
    muzzleFlashTint: 0xffb58d,
    projectileScale: 1.18,
    trailTint: 0xff9f7f,
    impactTint: 0xffbf94
  }),
  defineWeapon({
    id: "clusterLauncher",
    label: "Cluster Launcher",
    description: "Explosive shell that splits into extra fragments.",
    family: "explosive",
    tier: 3,
    behaviorKind: "rocketOrGrenade",
    tags: ["explosive"],
    visualKind: "grenade",
    impactKind: "explosive",
    behaviorConfig: { explosionRadius: 48, explosionDamage: 3.8 },
    fireRateMs: 1460,
    damage: 2.6,
    baseProjectiles: 2,
    projectileSpeed: 420,
    tint: 0xff9e8f,
    spreadCapDeg: 20,
    iconKey: iconKey("clusterLauncher"),
    previewPattern: "explosive",
    muzzleFlashTint: 0xffc8ba,
    projectileScale: 1.08,
    trailTint: 0xffb1a4,
    impactTint: 0xffc7c0
  }),
  defineWeapon({
    id: "mineLayer",
    label: "Mine Layer",
    description: "Drops armed charges that punish pursuit.",
    family: "explosive",
    tier: 3,
    behaviorKind: "mineDeploy",
    tags: ["explosive"],
    visualKind: "mine",
    impactKind: "explosive",
    behaviorConfig: { explosionRadius: 54, explosionDamage: 4.2, helperCap: 8, mineArmMs: 550, mineLifetimeMs: 4_800 },
    fireRateMs: 820,
    damage: 2.4,
    baseProjectiles: 1,
    projectileSpeed: 0,
    tint: 0xe5aa68,
    spreadCapDeg: 0,
    iconKey: iconKey("mineLayer"),
    previewPattern: "explosive",
    muzzleFlashTint: 0xffcf93,
    trailTint: 0xe5aa68,
    impactTint: 0xffd39b
  }),
  defineWeapon({
    id: "shockBomb",
    label: "Shock Bomb",
    description: "Explosive pulses with a wider stun-like pop.",
    family: "explosive",
    tier: 3,
    behaviorKind: "rocketOrGrenade",
    tags: ["explosive", "lightning"],
    visualKind: "grenade",
    impactKind: "explosive",
    behaviorConfig: { explosionRadius: 58, explosionDamage: 3.2 },
    fireRateMs: 1280,
    damage: 2.1,
    baseProjectiles: 1,
    projectileSpeed: 390,
    tint: 0xf1d775,
    spreadCapDeg: 14,
    iconKey: iconKey("shockBomb"),
    previewPattern: "explosive",
    muzzleFlashTint: 0xfff0aa,
    projectileScale: 1.14,
    trailTint: 0xf1d775,
    impactTint: 0xfff2b8
  })
] satisfies WeaponDef[];
