import type { WeaponDef } from "../../types";
import { defineWeapon, iconKey } from "./shared";

export const ORBITAL_WEAPONS: WeaponDef[] = [
  defineWeapon({
    id: "droneGun",
    label: "Drone Gun",
    description: "Deploys a fast drone that fires around you.",
    family: "orbital",
    tier: 3,
    behaviorKind: "orbitalHelper",
    tags: ["orbital"],
    visualKind: "orbital",
    impactKind: "orbital",
    behaviorConfig: { helperCap: 2, helperCount: 1, helperFireRateMs: 1_050, helperRadius: 72 },
    fireRateMs: 1_100,
    damage: 1.4,
    baseProjectiles: 1,
    projectileSpeed: 560,
    tint: 0xb5ecff,
    spreadCapDeg: 12,
    iconKey: iconKey("droneGun"),
    previewPattern: "orbit",
    muzzleFlashTint: 0xe0f9ff,
    trailTint: 0xb5ecff
  }),
  defineWeapon({
    id: "orbitingBlades",
    label: "Orbiting Blades",
    description: "Spinning cutters that intercept close threats.",
    family: "orbital",
    tier: 3,
    behaviorKind: "orbitalHelper",
    tags: ["orbital"],
    visualKind: "orbital",
    impactKind: "orbital",
    behaviorConfig: { helperCap: 4, helperCount: 2, helperRadius: 84, helperFireRateMs: 520 },
    fireRateMs: 1_200,
    damage: 1.3,
    baseProjectiles: 1,
    projectileSpeed: 0,
    tint: 0xf2efc4,
    spreadCapDeg: 0,
    iconKey: iconKey("orbitingBlades"),
    previewPattern: "orbit",
    muzzleFlashTint: 0xfff7d9,
    trailTint: 0xf2efc4
  }),
  defineWeapon({
    id: "energySatellites",
    label: "Energy Satellites",
    description: "Orbital nodes pulse energy through nearby crowds.",
    family: "orbital",
    tier: 3,
    behaviorKind: "orbitalHelper",
    tags: ["orbital", "beam"],
    visualKind: "orbital",
    impactKind: "beam",
    behaviorConfig: { helperCap: 4, helperCount: 2, helperRadius: 96, helperFireRateMs: 980 },
    fireRateMs: 1_300,
    damage: 1.8,
    baseProjectiles: 1,
    projectileSpeed: 520,
    tint: 0xbfa6ff,
    spreadCapDeg: 0,
    iconKey: iconKey("energySatellites"),
    previewPattern: "orbit",
    muzzleFlashTint: 0xdfd2ff,
    trailTint: 0xbfa6ff
  }),
  defineWeapon({
    id: "defenseTurret",
    label: "Defense Turret",
    description: "Drops a temporary auto-turret near the player.",
    family: "orbital",
    tier: 3,
    behaviorKind: "orbitalHelper",
    tags: ["orbital"],
    visualKind: "orbital",
    impactKind: "hit",
    behaviorConfig: { helperCap: 2, helperCount: 1, helperRadius: 32, helperFireRateMs: 750 },
    fireRateMs: 1_500,
    damage: 1.7,
    baseProjectiles: 1,
    projectileSpeed: 540,
    tint: 0xa4c4ff,
    spreadCapDeg: 10,
    iconKey: iconKey("defenseTurret"),
    previewPattern: "orbit",
    muzzleFlashTint: 0xcddfff,
    trailTint: 0xa4c4ff
  }),
  defineWeapon({
    id: "autoSentry",
    label: "Auto Sentry",
    description: "Heavier sentry fire for longer fights.",
    family: "orbital",
    tier: 3,
    behaviorKind: "orbitalHelper",
    tags: ["orbital"],
    visualKind: "orbital",
    impactKind: "hit",
    behaviorConfig: { helperCap: 3, helperCount: 1, helperRadius: 42, helperFireRateMs: 620 },
    fireRateMs: 1_600,
    damage: 2.1,
    baseProjectiles: 1,
    projectileSpeed: 560,
    tint: 0xb1dcff,
    spreadCapDeg: 10,
    iconKey: iconKey("autoSentry"),
    previewPattern: "orbit",
    muzzleFlashTint: 0xd8ecff,
    trailTint: 0xb1dcff
  })
] satisfies WeaponDef[];
