import type { WeaponDef } from "../../types";
import { defineWeapon, iconKey } from "./shared";

export const PRECISION_WEAPONS: WeaponDef[] = [
  defineWeapon({
    id: "railgun",
    label: "Railgun",
    description: "Long-range slug that tears through columns.",
    family: "precision",
    tier: 2,
    behaviorKind: "pierceShot",
    tags: ["precision"],
    visualKind: "bullet",
    impactKind: "beam",
    behaviorConfig: {},
    fireRateMs: 1600,
    damage: 6,
    baseProjectiles: 1,
    projectileSpeed: 720,
    tint: 0xa8f7ff,
    spreadCapDeg: 8,
    iconKey: iconKey("railgun"),
    previewPattern: "pierce",
    muzzleFlashTint: 0xdffcff,
    basePierce: 3,
    projectileScale: 1.14,
    trailTint: 0xa8f7ff
  }),
  defineWeapon({
    id: "laserRifle",
    label: "Laser Rifle",
    description: "Instant lance that rewards precise tracking.",
    family: "precision",
    tier: 2,
    behaviorKind: "beam",
    tags: ["beam", "precision"],
    visualKind: "beam",
    impactKind: "beam",
    behaviorConfig: { beamWidth: 18, beamLength: 300, beamDurationMs: 90 },
    fireRateMs: 820,
    damage: 2.8,
    baseProjectiles: 1,
    projectileSpeed: 800,
    tint: 0xff7c9b,
    spreadCapDeg: 6,
    iconKey: iconKey("laserRifle"),
    previewPattern: "beam",
    muzzleFlashTint: 0xffb3c3,
    trailTint: 0xff8ca7
  }),
  defineWeapon({
    id: "piercingRifle",
    label: "Piercing Rifle",
    description: "Clean line shots with dependable penetration.",
    family: "precision",
    tier: 2,
    behaviorKind: "pierceShot",
    tags: ["precision"],
    visualKind: "bullet",
    impactKind: "hit",
    behaviorConfig: {},
    fireRateMs: 950,
    damage: 2.4,
    baseProjectiles: 1,
    projectileSpeed: 660,
    tint: 0xc6dfff,
    spreadCapDeg: 10,
    iconKey: iconKey("piercingRifle"),
    previewPattern: "pierce",
    muzzleFlashTint: 0xe6f1ff,
    basePierce: 2,
    projectileScale: 1.02,
    trailTint: 0xc6dfff
  }),
  defineWeapon({
    id: "pulseCannon",
    label: "Pulse Cannon",
    description: "Heavy pulses that stagger clustered targets.",
    family: "precision",
    tier: 2,
    behaviorKind: "ballisticSingle",
    tags: ["precision"],
    visualKind: "bullet",
    impactKind: "hit",
    behaviorConfig: {},
    fireRateMs: 900,
    damage: 2.2,
    baseProjectiles: 1,
    projectileSpeed: 560,
    tint: 0x9cb3ff,
    spreadCapDeg: 12,
    iconKey: iconKey("pulseCannon"),
    previewPattern: "single",
    muzzleFlashTint: 0xc6d2ff,
    projectileScale: 1.2,
    trailTint: 0x9cb3ff
  }),
  defineWeapon({
    id: "plasmaShot",
    label: "Plasma Shot",
    description: "Dense orbs that burst through the center line.",
    family: "precision",
    tier: 2,
    behaviorKind: "ballisticSingle",
    tags: ["precision"],
    visualKind: "bullet",
    impactKind: "elemental",
    behaviorConfig: {},
    fireRateMs: 780,
    damage: 1.8,
    baseProjectiles: 2,
    projectileSpeed: 500,
    tint: 0xae9cff,
    spreadCapDeg: 12,
    iconKey: iconKey("plasmaShot"),
    previewPattern: "single",
    muzzleFlashTint: 0xddd3ff,
    projectileScale: 1.12,
    trailTint: 0xc2b4ff
  })
] satisfies WeaponDef[];
