import type { WeaponDef } from "../../types";
import { defineWeapon, iconKey } from "./shared";

export const SPREAD_WEAPONS: WeaponDef[] = [
  defineWeapon({
    id: "tripleShot",
    label: "Triple Shot",
    description: "Three tight shots on every pull.",
    family: "spread",
    tier: 1,
    behaviorKind: "fanSpread",
    tags: [],
    visualKind: "pellet",
    impactKind: "hit",
    behaviorConfig: {},
    fireRateMs: 760,
    damage: 1,
    baseProjectiles: 3,
    projectileSpeed: 545,
    tint: 0xcddf7d,
    spreadCapDeg: 22,
    iconKey: iconKey("tripleShot"),
    previewPattern: "fan",
    muzzleFlashTint: 0xe8f8a7,
    trailTint: 0xcddf7d
  }),
  defineWeapon({
    id: "quadShot",
    label: "Quad Shot",
    description: "Four-shot fan that keeps lanes saturated.",
    family: "spread",
    tier: 1,
    behaviorKind: "fanSpread",
    tags: [],
    visualKind: "pellet",
    impactKind: "hit",
    behaviorConfig: {},
    fireRateMs: 900,
    damage: 1,
    baseProjectiles: 4,
    projectileSpeed: 520,
    tint: 0xbbe68e,
    spreadCapDeg: 28,
    iconKey: iconKey("quadShot"),
    previewPattern: "fan",
    muzzleFlashTint: 0xddffb4,
    trailTint: 0xc4ec8f
  }),
  defineWeapon({
    id: "arcShot",
    label: "Arc Shot",
    description: "A curved fan that fills forward space.",
    family: "spread",
    tier: 1,
    behaviorKind: "fanSpread",
    tags: [],
    visualKind: "pellet",
    impactKind: "hit",
    behaviorConfig: {},
    fireRateMs: 1040,
    damage: 1.2,
    baseProjectiles: 5,
    projectileSpeed: 500,
    tint: 0x8fd6ff,
    spreadCapDeg: 34,
    iconKey: iconKey("arcShot"),
    previewPattern: "fan",
    muzzleFlashTint: 0xc4edff,
    projectileScale: 0.95,
    trailTint: 0x9bdfff
  }),
  defineWeapon({
    id: "wideShot",
    label: "Wide Shot",
    description: "Broad front for close-range crowd control.",
    family: "spread",
    tier: 1,
    behaviorKind: "fanSpread",
    tags: [],
    visualKind: "pellet",
    impactKind: "hit",
    behaviorConfig: {},
    fireRateMs: 1100,
    damage: 1.1,
    baseProjectiles: 6,
    projectileSpeed: 485,
    tint: 0xf0be7c,
    spreadCapDeg: 38,
    iconKey: iconKey("wideShot"),
    previewPattern: "fan",
    muzzleFlashTint: 0xffdfaa,
    projectileScale: 1.02,
    trailTint: 0xf4c891
  }),
  defineWeapon({
    id: "scatterBlaster",
    label: "Scatter Blaster",
    description: "A messy blast that blooms into dense forward chaos.",
    family: "spread",
    tier: 1,
    behaviorKind: "fanSpread",
    tags: [],
    visualKind: "pellet",
    impactKind: "hit",
    behaviorConfig: {},
    fireRateMs: 1300,
    damage: 1.3,
    baseProjectiles: 8,
    projectileSpeed: 470,
    tint: 0xf08484,
    spreadCapDeg: 40,
    iconKey: iconKey("scatterBlaster"),
    previewPattern: "fan",
    muzzleFlashTint: 0xffb0a2,
    projectileScale: 1.08,
    trailTint: 0xef9e9e
  })
] satisfies WeaponDef[];
