import type { WeaponDef } from "../../types";
import { defineWeapon, iconKey } from "./shared";

export const STARTER_WEAPONS: WeaponDef[] = [
  defineWeapon({
    id: "assaultRifle",
    label: "Assault Rifle",
    description: "Disciplined burst rifle for steady frontline pressure.",
    family: "basic",
    tier: 1,
    rarity: "common",
    availability: "starterOnly",
    behaviorKind: "ballisticBurst",
    tags: [],
    visualKind: "bullet",
    impactKind: "hit",
    behaviorConfig: {
      burstCount: 3,
      burstIntervalMs: 85
    },
    fireRateMs: 640,
    damage: 1.15,
    baseProjectiles: 1,
    projectileSpeed: 560,
    tint: 0xd0db8b,
    spreadCapDeg: 16,
    iconKey: iconKey("assaultRifle"),
    previewPattern: "burst",
    muzzleFlashTint: 0xe9f4ae,
    burstCount: 3,
    burstIntervalMs: 85,
    trailTint: 0xd4e48d
  }),
  defineWeapon({
    id: "sniperRifle",
    label: "Sniper Rifle",
    description: "High-impact rifle built for decisive precision shots.",
    family: "precision",
    tier: 2,
    rarity: "rare",
    availability: "starterOnly",
    behaviorKind: "pierceShot",
    tags: ["precision"],
    visualKind: "bullet",
    impactKind: "hit",
    behaviorConfig: {},
    fireRateMs: 1320,
    damage: 4.6,
    baseProjectiles: 1,
    projectileSpeed: 650,
    tint: 0xaee6ff,
    spreadCapDeg: 10,
    iconKey: iconKey("sniperRifle"),
    previewPattern: "pierce",
    muzzleFlashTint: 0xe0f8ff,
    basePierce: 2,
    projectileScale: 1.08,
    trailTint: 0xbdefff
  }),
  defineWeapon({
    id: "acidSprayer",
    label: "Acid Sprayer",
    description: "Short corrosive cone that saturates targets with venom.",
    family: "elemental",
    tier: 2,
    rarity: "rare",
    availability: "starterOnly",
    behaviorKind: "streamDot",
    tags: ["acid", "poison"],
    visualKind: "flame",
    impactKind: "elemental",
    behaviorConfig: {
      shortLifetimeMs: 460
    },
    fireRateMs: 200,
    damage: 0.9,
    baseProjectiles: 3,
    projectileSpeed: 430,
    tint: 0x9cf68a,
    spreadCapDeg: 28,
    iconKey: iconKey("acidSprayer"),
    previewPattern: "stream",
    muzzleFlashTint: 0xc8ff89,
    projectileScale: 0.86,
    trailTint: 0xa8f191
  }),
  defineWeapon({
    id: "turretLauncher",
    label: "Turret Launcher",
    description: "Deploys a rotating helper shot from a stable orbit lane.",
    family: "orbital",
    tier: 3,
    rarity: "epic",
    availability: "starterOnly",
    behaviorKind: "orbitalHelper",
    tags: ["orbital"],
    visualKind: "orbital",
    impactKind: "orbital",
    behaviorConfig: {
      helperCap: 1,
      helperCount: 1,
      helperRadius: 86
    },
    fireRateMs: 980,
    damage: 1.65,
    baseProjectiles: 1,
    projectileSpeed: 530,
    tint: 0x8dd9ff,
    spreadCapDeg: 12,
    iconKey: iconKey("turretLauncher"),
    previewPattern: "orbit",
    muzzleFlashTint: 0xd3f4ff,
    trailTint: 0x9ae7ff
  }),
  defineWeapon({
    id: "dualBlades",
    label: "Dual Blades",
    description: "Returning blades that reward aggressive close-range tempo.",
    family: "exotic",
    tier: 2,
    rarity: "rare",
    availability: "starterOnly",
    behaviorKind: "boomerangReturn",
    tags: ["bounce"],
    visualKind: "boomerang",
    impactKind: "hit",
    behaviorConfig: {
      returnDelayMs: 260
    },
    fireRateMs: 540,
    damage: 1.35,
    baseProjectiles: 2,
    projectileSpeed: 500,
    tint: 0xffa76f,
    spreadCapDeg: 18,
    iconKey: iconKey("dualBlades"),
    previewPattern: "chain",
    muzzleFlashTint: 0xffc798,
    projectileScale: 0.94,
    trailTint: 0xffb482
  }),
  defineWeapon({
    id: "lightningStaff",
    label: "Lightning Staff",
    description: "Focused storm conduit that chains power through packs.",
    family: "elemental",
    tier: 3,
    rarity: "epic",
    availability: "starterOnly",
    behaviorKind: "chainCaster",
    tags: ["lightning"],
    visualKind: "lightning",
    impactKind: "chain",
    behaviorConfig: {
      chainTargets: 2,
      chainDamageMultiplier: 0.58,
      chainRange: 210
    },
    fireRateMs: 860,
    damage: 2.2,
    baseProjectiles: 1,
    projectileSpeed: 560,
    tint: 0xaed9ff,
    spreadCapDeg: 14,
    iconKey: iconKey("lightningStaff"),
    previewPattern: "chain",
    muzzleFlashTint: 0xe4f2ff,
    trailTint: 0xc5e2ff
  }),
  defineWeapon({
    id: "shieldBlaster",
    label: "Shield Blaster",
    description: "Defensive launcher with steady recoil and safe spacing.",
    family: "basic",
    tier: 1,
    rarity: "common",
    availability: "starterOnly",
    behaviorKind: "ballisticSingle",
    tags: [],
    visualKind: "bullet",
    impactKind: "hit",
    behaviorConfig: {},
    fireRateMs: 900,
    damage: 1.1,
    baseProjectiles: 1,
    projectileSpeed: 500,
    tint: 0x9ed2ff,
    spreadCapDeg: 14,
    iconKey: iconKey("shieldBlaster"),
    previewPattern: "single",
    muzzleFlashTint: 0xd4ecff,
    projectileScale: 1.14,
    trailTint: 0xaddbff
  }),
  defineWeapon({
    id: "longbow",
    label: "Longbow",
    description: "Measured arrows with clean velocity and line pressure.",
    family: "precision",
    tier: 1,
    rarity: "common",
    availability: "starterOnly",
    behaviorKind: "pierceShot",
    tags: ["precision"],
    visualKind: "bullet",
    impactKind: "hit",
    behaviorConfig: {},
    fireRateMs: 980,
    damage: 1.8,
    baseProjectiles: 1,
    projectileSpeed: 620,
    tint: 0xd9c89a,
    spreadCapDeg: 10,
    iconKey: iconKey("longbow"),
    previewPattern: "pierce",
    muzzleFlashTint: 0xf0ddb1,
    basePierce: 1,
    trailTint: 0xe0cea1
  }),
  defineWeapon({
    id: "throwingDaggers",
    label: "Throwing Daggers",
    description: "Fast precision knives that bloom into a narrow forward fan.",
    family: "precision",
    tier: 3,
    rarity: "epic",
    availability: "starterOnly",
    behaviorKind: "fanSpread",
    tags: ["precision"],
    visualKind: "pellet",
    impactKind: "hit",
    behaviorConfig: {},
    fireRateMs: 690,
    damage: 1.05,
    baseProjectiles: 3,
    projectileSpeed: 610,
    tint: 0xf2f0ff,
    spreadCapDeg: 16,
    iconKey: iconKey("throwingDaggers"),
    previewPattern: "fan",
    muzzleFlashTint: 0xffffff,
    projectileScale: 0.82,
    trailTint: 0xdfdcff
  }),
  defineWeapon({
    id: "boneWand",
    label: "Bone Wand",
    description: "Ancient focus that lashes multiple targets with cursed force.",
    family: "exotic",
    tier: 4,
    rarity: "legendary",
    availability: "starterOnly",
    behaviorKind: "chainCaster",
    tags: ["orbital"],
    visualKind: "lightning",
    impactKind: "chain",
    behaviorConfig: {
      chainTargets: 3,
      chainDamageMultiplier: 0.62,
      chainRange: 235
    },
    fireRateMs: 880,
    damage: 2.9,
    baseProjectiles: 1,
    projectileSpeed: 540,
    tint: 0xf7e3c0,
    spreadCapDeg: 12,
    iconKey: iconKey("boneWand"),
    previewPattern: "chain",
    muzzleFlashTint: 0xffefd5,
    trailTint: 0xf4dfbd
  }),
  defineWeapon({
    id: "spear",
    label: "Spear",
    description: "Linear thrust weapon that rewards clean lane control.",
    family: "precision",
    tier: 1,
    rarity: "common",
    availability: "starterOnly",
    behaviorKind: "pierceShot",
    tags: ["precision"],
    visualKind: "bullet",
    impactKind: "hit",
    behaviorConfig: {},
    fireRateMs: 830,
    damage: 1.7,
    baseProjectiles: 1,
    projectileSpeed: 540,
    tint: 0xe0b17d,
    spreadCapDeg: 8,
    iconKey: iconKey("spear"),
    previewPattern: "pierce",
    muzzleFlashTint: 0xf2c99a,
    basePierce: 2,
    trailTint: 0xe9bc89
  }),
  defineWeapon({
    id: "bombLauncher",
    label: "Bomb Launcher",
    description: "Lobbed explosives built for volatile crowd breaks.",
    family: "explosive",
    tier: 2,
    rarity: "rare",
    availability: "starterOnly",
    behaviorKind: "rocketOrGrenade",
    tags: ["explosive"],
    visualKind: "grenade",
    impactKind: "explosive",
    behaviorConfig: {
      explosionRadius: 46,
      explosionDamage: 2.5
    },
    fireRateMs: 1180,
    damage: 1.7,
    baseProjectiles: 1,
    projectileSpeed: 420,
    tint: 0xff9368,
    spreadCapDeg: 18,
    iconKey: iconKey("bombLauncher"),
    previewPattern: "explosive",
    muzzleFlashTint: 0xffbd95,
    trailTint: 0xffa37d
  }),
  defineWeapon({
    id: "ricochetGun",
    label: "Ricochet Gun",
    description: "Mischievous repeater with lively rebounds and angle play.",
    family: "exotic",
    tier: 2,
    rarity: "rare",
    availability: "starterOnly",
    behaviorKind: "boomerangReturn",
    tags: ["bounce"],
    visualKind: "boomerang",
    impactKind: "chain",
    behaviorConfig: {
      returnDelayMs: 300
    },
    fireRateMs: 660,
    damage: 1.15,
    baseProjectiles: 1,
    projectileSpeed: 570,
    tint: 0xa6b6ff,
    spreadCapDeg: 12,
    iconKey: iconKey("ricochetGun"),
    previewPattern: "chain",
    muzzleFlashTint: 0xd8deff,
    projectileScale: 0.9,
    trailTint: 0xb7c5ff
  })
] satisfies WeaponDef[];
